Restarted Python 3.14.3

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Имя': ['Анна', 'Петр', 'Елена', 'Сергей', 'Мария', 'Иван'],
    'Возраст': [25, 30, 28, '35 лет', 22, np.nan],
    'Город': ['Москва', 'спб', 'Москва', 'Казань', 'спб', 'Москва'],
    'Опыт_работы_лет': [2, 5, 1, 7, 0, np.nan],
    'Продуктивность_%': [105, 98, 110, '95%', 88, 102] 
}

df = pd.DataFrame(data)
print(df)

      Имя Возраст   Город  Опыт_работы_лет Продуктивность_%
0    Анна      25  Москва              2.0              105
1    Петр      30     спб              5.0               98
2   Елена      28  Москва              1.0              110
3  Сергей  35 лет  Казань              7.0              95%
4   Мария      22     спб              0.0               88
5    Иван     NaN  Москва              NaN              102

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Имя               6 non-null      str
 1   Возраст           5 non-null      object
 2   Город             6 non-null      str
 3   Опыт_работы_лет   5 non-null      float64
 4   Продуктивность_%  6 non-null      object
dtypes: float64(1), object(2), str(2)
memory usage: 372.0+ bytes

In [ ]:
df.head()

      Имя Возраст   Город  Опыт_работы_лет Продуктивность_%
0    Анна      25  Москва              2.0              105
1    Петр      30     спб              5.0               98
2   Елена      28  Москва              1.0              110
3  Сергей  35 лет  Казань              7.0              95%
4   Мария      22     спб              0.0               88

In [ ]:

df['clean_age'] = df['Возраст'].astype(str)
df['clean_age'] = df['clean_age'].str.replace(r'[^0-9]','', regex=True)
df['clean_age']

0     25
1     30
2     28
3     35
4     22
5    NaN
Name: clean_age, dtype: str

In [ ]:
df['clean_age'] = pd.to_numeric(df['clean_age'], errors='coerce')
df['clean_age']

0    25.0
1    30.0
2    28.0
3    35.0
4    22.0
5     NaN
Name: clean_age, dtype: float64

In [ ]:
df['clean_age'] = df['clean_age'].fillna(df['clean_age'].mean())
df['clean_age']

0    25.0
1    30.0
2    28.0
3    35.0
4    22.0
5    28.0
Name: clean_age, dtype: float64

In [ ]:
df['Продуктивность_%']

0    105
1     98
2    110
3    95%
4     88
5    102
Name: Продуктивность_%, dtype: object

In [ ]:

df['clean_progres'] = df['Продуктивность_%'].astype(str)
df['clean_progres']

0    105
1     98
2    110
3    95%
4     88
5    102
Name: clean_progres, dtype: str

In [ ]:
df['clean_progres'] = df['clean_progres'].str.replace(r'[^0-9]','',regex=True)
df['clean_progres']

0    105
1     98
2    110
3     95
4     88
5    102
Name: clean_progres, dtype: str

In [ ]:
df['clean_city'] = df['Город'].str.strip().str.title()
df['clean_city']

0    Москва
1       Спб
2    Москва
3    Казань
4       Спб
5    Москва
Name: clean_city, dtype: str

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Имя               6 non-null      str
 1   Возраст           5 non-null      object
 2   Город             6 non-null      str
 3   Опыт_работы_лет   5 non-null      float64
 4   Продуктивность_%  6 non-null      object
 5   clean_age         6 non-null      float64
 6   clean_progres     6 non-null      str
 7   clean_city        6 non-null      str
dtypes: float64(2), object(2), str(4)
memory usage: 516.0+ bytes

In [ ]:
df['clean_experience'] = df['Опыт_работы_лет'].fillna(df['Опыт_работы_лет'].mean())
df['clean_experience']

0    2.0
1    5.0
2    1.0
3    7.0
4    0.0
5    3.0
Name: clean_experience, dtype: float64

In [ ]:
df['clean_experience'] = df['clean_experience'].round(0)
df['clean_experience']

0    2.0
1    5.0
2    1.0
3    7.0
4    0.0
5    3.0
Name: clean_experience, dtype: float64

In [ ]:
df['clean_progres'] = df['clean_progres'].astype(int)
df['clean_progres']

0    105
1     98
2    110
3     95
4     88
5    102
Name: clean_progres, dtype: int64

In [ ]:

df_mask = (df['clean_progres'] > 85) & (df['clean_experience'] < 1)
df_filter = df.loc[df_mask,['Имя', 'Возраст','clean_progres', 'clean_experience']]
df_filter

     Имя Возраст  clean_progres  clean_experience
4  Мария      22             88               0.0